### ISSUE TITLE
Milestone 1 - Layout Improvements

### ISSUE THREAD

**Issue by arkanoryn** [ratouney/janusow#13]
## General 
- [ ] Define a ColorPalette: default, primary, danger, success, info
- [ ] Create a README

## General Layout
- [x] logo resize
- [x] reduce button: fix the hover color
- [x] remove the `user` icon
- [x] remove the `logout` link
- [x] make one button `Guest >` instead of separated
- [x] add an icon in front of `Settings`
- [x] fix the `primary color` usage of the menu
- [x] add a margin on the `GUEST` button

## HomePage
- [x] fix the placeholders
- [x] fix the MasterRace
- [x] fix the search button size
- [x] fix the default `no content` on the table

## SideMenu
- [x] put the `Add Account` at the top of the menu, outside of the menu
- [x] put a `Fuse Account` disabled button
- [x] ~~make both button as `ButtonGroup`~~ (looks horrible when menu is collapsed)

**Comment by ratouney** [comment]
Only colors need to be added !

See #21
