### ISSUE TITLE
Milestone 2 - Add accounts

### ISSUE THREAD

**Issue by arkanoryn** [ratouney/janusow#14]
## General
- [x] Create a modal
- [x] Clicking on the button opens the Modal

## Form
- [x] Fix the placeholders
- [x] Hide Username
- [x] Radiobutton instead of select?
- [ ] Keep entries after error
- [x] Submit of 100% width

## Progress
- [x] Fix the resize display

**Comment by ratouney** [comment]
Openned a separate ticket for the missing part

See : https://github.com/ratouney/janusow/issues/17
