### ISSUE TITLE
Milestone 3 - Account

### ISSUE THREAD

**Issue by arkanoryn** [ratouney/janusow#15]
## General
- [x] Center the Avatar inside the card
- [x] Adapt the table size to the screen
- [x] Put the legends in **bold**

### List
- [x] Increase the font size
- [x] Change the color usage: font black/white or use the picture/hero color palette
- [x] Rework the column sizing to not have dead space/empty space
- [x] Add the avatar of the hero infront of his name
- [x] Adapt the font size accordingly

### PieChart
- [x]  Put a `minHeight` on the Card
- [x]  Research the margin on left/right
- [ ]  Research if it is possible to provide unit to the tooltips
([Requires alot of code](https://github.com/jerairrest/react-chartjs-2/issues/151))

### Hero
- [x] **bold** legends
- [x] Add an `extra` named `futher information` in the Hero Card ([RTFM](https://ant.design/components/card/#components-card-demo-basic))
- [x] Reduce the margin between the Avatar and the Table

### Cards
- [ ] Add a `bottom`||`top` margin on Cards so they stay visible on small devices

## Competitive
- [x] Put time entries on `Round` to get either full hours only or `hours:minutes`

**Comment by ratouney** [comment]
PieChart : 
- Tooltip customisation is postponed, as minor and seems to require alot of code for a small QoL change

Cards : 
- Not a prioritized rework.

Issues will be created if needed, currently these bugs will stay as WIP for now
